services:
    kinerity.topicdescriptions.listener:
        class: kinerity\topicdescriptions\event\listener
        arguments:
            - @auth
            - @dbal.conn
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
